/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vending_machine;

import java.awt.*;
import java.io.*;
import java.nio.file.*;
import javax.swing.*;

/**
 *
 * @author lim
 */
public class AddProduct extends javax.swing.JDialog {
    
    private Admin_page adminPageInstance;
    
    
    
    public void setAdminPageInstance(Admin_page adminPage) {
        this.adminPageInstance = adminPage;
    }
    private void getId(){
        int maximumNumber = 0;
        String line;
        try {
            BufferedReader bufferedReader = new BufferedReader(new FileReader("product\\product.txt"));

            while ((line = bufferedReader.readLine()) != null) {
                String[] lineArray = line.split(",");
                int currentNumber = Integer.parseInt(lineArray[0]);
                if (currentNumber > maximumNumber) {
                    //Get the maximum id in text file
                    maximumNumber = currentNumber;
                }
            }
            //The maximum number plus one to be the id
            maximumNumber = maximumNumber +1;
            bufferedReader.close();
            totalLine = Integer.toString(maximumNumber);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    /**
     * Creates new form AddProduct2
     */
    public AddProduct(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getId();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        lCategory = new javax.swing.JLabel();
        lPrice = new javax.swing.JLabel();
        lStock = new javax.swing.JLabel();
        lImage = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        tfStock = new javax.swing.JTextField();
        tfImageLocation = new javax.swing.JTextField();
        bChooseImage = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        cbCategory = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Product");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTitle.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lTitle.setText("Add Product");
        getContentPane().add(lTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        lName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lName.setText("Name:");
        getContentPane().add(lName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        lCategory.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lCategory.setText("Category:");
        getContentPane().add(lCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lPrice.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lPrice.setText("Price: MYR");
        getContentPane().add(lPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        lStock.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lStock.setText("Stock:");
        getContentPane().add(lStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        lImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 150, 150));
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 110, -1));
        getContentPane().add(tfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 180, 80, -1));
        getContentPane().add(tfStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 110, -1));

        tfImageLocation.setEditable(false);
        getContentPane().add(tfImageLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 270, -1));

        bChooseImage.setText("Choose");
        bChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChooseImageActionPerformed(evt);
            }
        });
        getContentPane().add(bChooseImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        bAdd.setText("Add");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });
        getContentPane().add(bAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Food", "Drink" }));
        getContentPane().add(cbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 110, -1));

        setSize(new java.awt.Dimension(614, 357));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        // TODO add your handling code here:
        //Check if any field is empty
        if (tfName.getText().isEmpty() ||cbCategory.getSelectedItem().equals("Please Select") || tfPrice.getText().isEmpty()|| tfStock.getText().isEmpty()|| tfImageLocation.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all fields.");
        }
        
        else {
            //Get the value from each text field
            String name = tfName.getText();
            String category = (String) cbCategory.getSelectedItem();
            String price = tfPrice.getText();
            String stock = tfStock.getText();
            StringBuilder product = new StringBuilder();
            
            //Check if price is numeric
            try{
                Double.parseDouble(price);
            }

            catch (Exception e)
                    {JOptionPane.showMessageDialog(null, "Please only insert numeric value in price.");
                    return;}
            
            //Check if stock is integer
            try{
                Integer.parseInt(stock);
            }

            catch (Exception e)
                    {JOptionPane.showMessageDialog(null, "Please only integer number in stock.");
                    return;}


             try {
                 
                //Write the information to the text file
                product.append(totalLine +","+name+"," + category + "," +price + "," +stock + "," + desFileName + ",Active");

                BufferedWriter writer = new BufferedWriter(new FileWriter("product\\product.txt", true));
                writer.write(product + "\n");
                writer.close();


            try {
                //Copy the image file to folder
                Files.copy(sourceFile.toPath(), destinationFile.toPath());

            } catch (Exception e) {
                e.getMessage();
            }



                } 
             catch (Exception e) {
                System.err.println(e.getMessage());
            }

            JOptionPane.showMessageDialog(null, "Successfully Added!");
            this.dispose();
            adminPageInstance.refreshTable("");
        }
        
        
        
    }//GEN-LAST:event_bAddActionPerformed

    private void bChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChooseImageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file=chooser.getSelectedFile();
        if (file != null){
        ImageIcon imageIcon = new ImageIcon(file.toString());
        Image setIcon = imageIcon.getImage().getScaledInstance(150,150, Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(setIcon);
        lImage.setIcon(img);
        
        String filePath = file.getAbsolutePath();
        tfImageLocation.setText(filePath);
        
        
        String path = "product/image";
        
        sourceFile = new File(filePath);
        
        String extension = filePath.substring(filePath.lastIndexOf(".")+1);
        
        
        destinationFile = new File (path+ "/product"+ totalLine+ "." + extension);
        desFileName = ("product"+ totalLine+ "." + extension);}
        
    }//GEN-LAST:event_bChooseImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddProduct dialog = new AddProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    private File sourceFile;
    private File destinationFile;
    private String desFileName;
    private String totalLine;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bChooseImage;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JLabel lCategory;
    private javax.swing.JLabel lImage;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lPrice;
    private javax.swing.JLabel lStock;
    private javax.swing.JLabel lTitle;
    private javax.swing.JTextField tfImageLocation;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfStock;
    // End of variables declaration//GEN-END:variables
}
