/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vending_machine;

import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.text.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author lim
 */


public class Admin_page extends javax.swing.JFrame {
    
    
    
    public void refreshTable(String nameOfProduct) {
        DefaultTableModel model = (DefaultTableModel)tProductList.getModel();
        model.setRowCount(0);
        String line;
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("product\\product.txt"));
            while ((line = br.readLine()) != null) {
                String[] record = line.split(",");
                if (record[1].toLowerCase().startsWith(nameOfProduct)) {
                    //Get the location of image
                    String imageLocation = "product\\image\\" +record[5];
                    //Set the image properties
                    ImageIcon imageIcon = new ImageIcon(imageLocation);
                    Image setIcon = imageIcon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                    ImageIcon img = new ImageIcon(setIcon);

                    //Add the record to Table
                    model.addRow(record);

                    int rowIndex = model.getRowCount() - 1;
                    int columnIndex = model.getColumnCount() - 2;
                    //set Image to the Table
                    tProductList.setValueAt(img, rowIndex, columnIndex);
                    }
                }
            br.close();
        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    private void createDatetimeUpdater() {
        // Every one second trigger the updateDatetime
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateDatetime();
            }
        });
        timer.start();
    }
    
    private void updateDatetime() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String datetime = sdf.format(new Date());
        lDateTime.setText(datetime);
    }
    
    
    Class_VM fp = new Class_VM();
    
    
    
    /**
     * Creates new form admin
     */
    public Admin_page() {
        initComponents();
        refreshTable("");
        createDatetimeUpdater();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAdd = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        spProductList = new javax.swing.JScrollPane();
        tProductList = new javax.swing.JTable();
        bDelete = new javax.swing.JButton();
        bGenerateReport = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        bMoveUp = new javax.swing.JButton();
        bMoveDown = new javax.swing.JButton();
        bBackToCP = new javax.swing.JButton();
        lTitle = new javax.swing.JLabel();
        lDateTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bAdd.setText("Add");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });
        getContentPane().add(bAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 110, -1));

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        getContentPane().add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 110, -1));

        tProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Price(MYR)", "Stock", "Image", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, javax.swing.Icon.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tProductList.setRowHeight(80);
        tProductList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tProductList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tProductListMouseClicked(evt);
            }
        });
        spProductList.setViewportView(tProductList);

        getContentPane().add(spProductList, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 164, 639, 630));

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 110, -1));

        bGenerateReport.setText("Genrate Report");
        bGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenerateReportActionPerformed(evt);
            }
        });
        getContentPane().add(bGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });
        getContentPane().add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 368, -1));

        bMoveUp.setText("Move Up");
        bMoveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMoveUpActionPerformed(evt);
            }
        });
        getContentPane().add(bMoveUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 110, -1));

        bMoveDown.setText("Move Down");
        bMoveDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMoveDownActionPerformed(evt);
            }
        });
        getContentPane().add(bMoveDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 110, -1));

        bBackToCP.setText("Back to Customer Page");
        bBackToCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackToCPActionPerformed(evt);
            }
        });
        getContentPane().add(bBackToCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lTitle.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        lTitle.setText("Admin Page");
        getContentPane().add(lTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 706, 60));

        lDateTime.setText("DateTime");
        getContentPane().add(lDateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        setSize(new java.awt.Dimension(814, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        // TODO add your handling code here:
        
        //Open AddProduct page
        AddProduct ap = new AddProduct(this,true);
        
        ap.pack();
        ap.setLocationRelativeTo(null);
        
        ap.setAdminPageInstance(this);
        ap.setVisible(true);

    }//GEN-LAST:event_bAddActionPerformed

    private void tProductListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tProductListMouseClicked
        // TODO add your handling code here:
        int count = -1;
        selectedRecord = tProductList.getSelectedRow();
        
        //The id of the select record
        String selectionID = tProductList.getModel().getValueAt(tProductList.getSelectedRow(), 0).toString();
        
        //Read the line in file and get the actual row line in the file
        try (BufferedReader reader = new BufferedReader(new FileReader("product\\product.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] lineArray = line.split(",");
                    count = count + 1;
                if (selectionID.equals(lineArray[0])) {
                    break;
                }
            }
        //Replaced selectedRecord to actual row line    
        selectedRecord = count;
        } catch (Exception e) {
            e.getMessage();
        }
        
    }//GEN-LAST:event_tProductListMouseClicked

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
         // TODO add your handling code here:
    EditProduct ep = new EditProduct(this,true);
        if (selectedRecord != -1) {
            //Get the selected record
            String[] record = fp.getProductRecord(selectedRecord);
            
            //Set and pass record and this page to EditProduct
            ep.setAdminPageInstance(this);
            ep.setRecordData(record);
            ep.getRow(selectedRecord);
            
            //Open EditProduct page
            ep.setVisible(true);
        }
        else{
            //If no selected then notify user to select
            JOptionPane.showMessageDialog(null, "Please select a product to edit!");
        }
    }//GEN-LAST:event_bEditActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
        List<String> lines = fp.getAllProductRecord();
        
        int currentIndex = -1;
        
        if (selectedRecord != -1) {
            String[] record = fp.getProductRecord(selectedRecord);
            lines.set(selectedRecord, "");
            //Show up dialog to confirm delete
            int option=JOptionPane.showConfirmDialog(null,"Do you want to remove this item from your cart?","Remove Item",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
            if(option==JOptionPane.YES_OPTION){
                //Delete the record
                try {
                    BufferedWriter writer = new BufferedWriter(new FileWriter("product\\product.txt"));
                    for (String updatedLine : lines) {
                        currentIndex++;
                        //skip the speific record
                        if (currentIndex == selectedRecord) {
                            continue;
                        }
                        else {
                        //rewrite other line to file
                        writer.write(updatedLine);
                        writer.newLine();
                        }
                    }
                    writer.close();
                    }
                
                 catch (Exception e) {
                    e.getMessage();
                }
                //delete the old image
                File oldFile = new File ("product\\image\\" + record[5]);
                oldFile.delete();
                
                //Show message dialog to present the record has been delete
                JOptionPane.showMessageDialog(null, "Successfully Deleted!");
            }
        }
        else{
            //If no product was selected, pop up to notify user to choose product
            JOptionPane.showMessageDialog(null, "Please select a product to delete!");
            }
        refreshTable("");
    }//GEN-LAST:event_bDeleteActionPerformed

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        // TODO add your handling code here:
        String name = tfSearch.getText().toLowerCase();
        refreshTable(name);
    }//GEN-LAST:event_tfSearchKeyReleased

    private void bMoveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMoveUpActionPerformed
        // TODO add your handling code here:
        String line;
        List<String> lines = new ArrayList<>();
        
        try (
            BufferedReader reader = new BufferedReader(new FileReader("product\\product.txt"))
        ){  //Read and add all the lines in file to line
            while ((line = reader.readLine()) != null) {
                lines.add(line);
            }
        reader.close();
        } catch (Exception e) {
            e.getMessage();
        }
        
        if (selectedRecord > 0) {
            //swap the line
            Collections.swap(lines, selectedRecord, selectedRecord - 1);
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("product\\product.txt"))) {
                for (String updatedLine : lines) {
                    //rewrite the whole line to file.
                    writer.write(updatedLine);
                    writer.newLine();
                }
            writer.close();
            } catch (Exception e) {
                e.getMessage();
            }
        } else {
            //If user choose the top product
            JOptionPane.showMessageDialog(null, "This item is already at the top");
        }
    refreshTable("");
    selectedRecord =selectedRecord - 1;
    }//GEN-LAST:event_bMoveUpActionPerformed

    private void bMoveDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMoveDownActionPerformed
        // TODO add your handling code here:
        String line;
        List<String> lines = new ArrayList<>();
        
        try (BufferedReader reader = new BufferedReader(new FileReader("product\\product.txt"))) {
            while ((line = reader.readLine()) != null) {
                ////Read and add all the lines in file to line
                lines.add(line);
            }
        reader.close();
        } catch (Exception e) {
            e.getMessage();
        }
        if (selectedRecord < lines.size() - 1) {
            //swap the line
            Collections.swap(lines, selectedRecord, selectedRecord + 1);
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("product\\product.txt"))) {
                for (String updatedLine : lines) {
                    //rewrite the whole line to file.
                    writer.write(updatedLine);
                    writer.newLine();
                }
            } catch (Exception e) {
                e.getMessage();
            }
        } else {
            //If user choose the bottom product
            JOptionPane.showMessageDialog(null, "This item is already at the bottom");
        }
    refreshTable("");
    selectedRecord =selectedRecord + 1;
    }//GEN-LAST:event_bMoveDownActionPerformed

    private void bGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenerateReportActionPerformed
        // TODO add your handling code here:
        //Open Generate Report page
        Generate_report gr = new Generate_report(this,true);
        
        gr.pack();
        gr.setLocationRelativeTo(null);
        gr.setVisible(true);
        
    }//GEN-LAST:event_bGenerateReportActionPerformed

    private void bBackToCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackToCPActionPerformed
        // TODO add your handling code here:
        //Back to Custoemr Page
        this.dispose();
        
        Customer_page cp = new Customer_page();
        
        
        cp.pack();
        cp.setLocationRelativeTo(null);
        cp.setVisible(true);
        
        
    }//GEN-LAST:event_bBackToCPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_page().setVisible(true);
            }
        });
    }

    private int selectedRecord = -1;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bBackToCP;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bGenerateReport;
    private javax.swing.JButton bMoveDown;
    private javax.swing.JButton bMoveUp;
    private javax.swing.JLabel lDateTime;
    private javax.swing.JLabel lTitle;
    private javax.swing.JScrollPane spProductList;
    private javax.swing.JTable tProductList;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
