/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vending_machine;

import java.io.*;
import java.time.*;
import java.time.format.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author lim
 */
public class Customer_purchase extends javax.swing.JDialog {
    
    
    private String[][] cartRecord;
    public void setCartRecords(String[][] cartRecords) {
        this.cartRecord = cartRecords;
    }
    
    
    private Customer_page customerPageInstance;
    
    public void setAdminPageInstance(Customer_page Customer_page) {
        this.customerPageInstance = Customer_page;
    }
    
    Class_VM fp = new Class_VM();
    
    

    /**
     * Creates new form Customer_purchase2
     */
    public Customer_purchase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTotalMoneyValue = new javax.swing.JLabel();
        tfMoneyValue = new javax.swing.JTextField();
        bPay = new javax.swing.JButton();
        lMYR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pay");
        setResizable(false);

        lTotalMoneyValue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lTotalMoneyValue.setText("What total value of momey you inserted:");

        tfMoneyValue.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N

        bPay.setText("Pay");
        bPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPayActionPerformed(evt);
            }
        });

        lMYR.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        lMYR.setText("MYR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lTotalMoneyValue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(bPay))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lMYR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMoneyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lTotalMoneyValue)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMoneyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMYR))
                .addGap(10, 10, 10)
                .addComponent(bPay)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(414, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPayActionPerformed
        // TODO add your handling code here:
        //Get all lines in text file
        List<String> lines = fp.getAllProductRecord();
        boolean flag= false;
        double floMoneyInserted = 0;
        
       try {
           //Check if the money is numeric
            String moneyInserted = tfMoneyValue.getText();
            floMoneyInserted = Double.parseDouble(moneyInserted);
            flag = true; // Move the flag assignment here
        }
        catch (NumberFormatException e) {
            // Handle invalid number format if needed
            JOptionPane.showMessageDialog(null, "Invalid Money!");
        }

        double totalSum = 0.0f;
        
        for (int i = 0; i < cartRecord.length; i++) {
            //Get the total sum price value in cart
            String valueAsString = cartRecord[i][3];
            double value = Double.parseDouble(valueAsString);
            double qut = Double.parseDouble(cartRecord[i][2]);
            
            double totalPrice = qut * value;
            totalSum += totalPrice;
        }
        
        double balance = floMoneyInserted - totalSum;
        String strBalance = Double.toString(balance);
        
        if (flag && floMoneyInserted >= totalSum) {
            //If user has enough money
            try {//Write the record of this sales to a textfile
                BufferedWriter writer = new BufferedWriter(new FileWriter("log\\SalesLog.txt", true));
                    for (int i = 0; i < cartRecord.length; i++) {
                        for (int j = 0; j < cartRecord[i].length; j++) {
                            LocalDateTime currentDateTime = LocalDateTime.now();
                            DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                            DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

                            String formattedDate = currentDateTime.format(dateFormatter);
                            String formattedTime = currentDateTime.format(timeFormatter);

                            String strRecord = Arrays.toString(cartRecord[i]);
                            writer.write(formattedDate + ","+ formattedTime + ",");
                            strRecord = strRecord.replaceAll(", ", ",");
                            strRecord = strRecord.substring(1, strRecord.length() - 1);
                            writer.write(strRecord+ "\n");

                            break;
                        }
                    }
                writer.close();
                } 
            catch (Exception e) {
                System.err.println(e.getMessage());
            }
        
            try {
                //Get the new stock number
                BufferedReader br = new BufferedReader(new FileReader("product\\product.txt")); 
                String line;
                int count = -1;
                while ((line = br.readLine()) != null) {
                    String[] record = line.split(",");
                    count ++;
                    for (int i = 0; i < cartRecord.length; i++) {  
                        if (cartRecord[i][0].equals(record[0])) {
                            int stoQut = Integer.parseInt(record[4]);
                            int cartQut = Integer.parseInt(cartRecord[i][3]);
                            int newQuantity = stoQut - cartQut;
                            
                            //Change to the new stock and store it in variable lines
                            record[4] = String.valueOf(newQuantity);
                            String strRecord = Arrays.toString(record);
                            strRecord = strRecord.replaceAll(", ", ",");
                            strRecord = strRecord.substring(1, strRecord.length() - 1);
                            lines.set(count, strRecord);
                        }
                    }
                    
                }
                
                //Write the new lines to the text file
                try {BufferedWriter writer = new BufferedWriter(new FileWriter("product\\product.txt"));
                    for (String updatedLine : lines) {
                        writer.write(updatedLine);
                         writer.newLine();
                    }
                writer.close();
                }
                catch (Exception e) {
                        System.err.println( e.getMessage());
                }
            }                
            catch (Exception e) {
                    System.err.println(e.getMessage());
                }
        JOptionPane.showMessageDialog(null, "Your balance is "+ strBalance);    
        
        //Set the cartRecord to 0 and refresh the cart
        cartRecord = new String[0][0];
        customerPageInstance.setCartRecord(cartRecord);
        this.dispose();
        }
        else if (flag && (floMoneyInserted < totalSum)){
            //If user money is not enough
            JOptionPane.showMessageDialog(null, "No enough money!");
        }
        
    }//GEN-LAST:event_bPayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Customer_purchase dialog = new Customer_purchase(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPay;
    private javax.swing.JLabel lMYR;
    private javax.swing.JLabel lTotalMoneyValue;
    private javax.swing.JTextField tfMoneyValue;
    // End of variables declaration//GEN-END:variables
}
