/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vending_machine;

import java.awt.Image;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author lim
 */
public class EditProduct extends javax.swing.JDialog {

    /**
     * Creates new form EditProduct2
     */
    public EditProduct(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private Admin_page adminPageInstance;
    private String[] recordData; 
    private int row;
    Class_VM fp = new Class_VM();
    
    public void setRecordData(String[] record) {
        this.recordData = record;
        //Get the value from text field
        tfName.setText(record[1]);
        cbCategory.setSelectedItem(record[2]);
        tfPrice.setText(record[3]);
        tfStock.setText(record[4]);
        cbStatus.setSelectedItem(record[6]);
        
        //Set the Image
        String image = record[5];
        String imageLocation = "product\\image\\" +image;
        ImageIcon imageIcon = new ImageIcon(imageLocation);
        Image setIcon = imageIcon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(setIcon);
        lImage.setIcon(img);
        tfImageLocation.setText(imageLocation);
    }
    
    public void getRow(int selectedRecord) {
        //Get the row in text file of the record
        this.row = selectedRecord;
        System.out.println("row:" +row);
    }
    
    public void setAdminPageInstance(Admin_page adminPage) {
        this.adminPageInstance = adminPage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        lCategory = new javax.swing.JLabel();
        lPrice = new javax.swing.JLabel();
        lStock = new javax.swing.JLabel();
        lStatus = new javax.swing.JLabel();
        lImage = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        cbCategory = new javax.swing.JComboBox<>();
        tfPrice = new javax.swing.JTextField();
        tfStock = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        tfImageLocation = new javax.swing.JTextField();
        bChooseImage = new javax.swing.JButton();
        bSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Product");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTitle.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lTitle.setText("Edit Product");
        getContentPane().add(lTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        lName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lName.setText("Name:");
        getContentPane().add(lName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        lCategory.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lCategory.setText("Category:");
        getContentPane().add(lCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lPrice.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lPrice.setText("Price: MYR");
        getContentPane().add(lPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        lStock.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lStock.setText("Stock:");
        getContentPane().add(lStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lStatus.setText("Status:");
        getContentPane().add(lStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        lImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 150, 150));
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 130, -1));

        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Drink" }));
        getContentPane().add(cbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 130, -1));
        getContentPane().add(tfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 100, -1));
        getContentPane().add(tfStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 130, -1));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Disable" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });
        getContentPane().add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 130, -1));

        tfImageLocation.setEditable(false);
        getContentPane().add(tfImageLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 260, -1));

        bChooseImage.setText("Choose");
        bChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChooseImageActionPerformed(evt);
            }
        });
        getContentPane().add(bChooseImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        getContentPane().add(bSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        setSize(new java.awt.Dimension(614, 357));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChooseImageActionPerformed
        // TODO add your handling code here:
        //Get the file choose
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file=chooser.getSelectedFile();
        ImageIcon imageIcon = new ImageIcon(file.toString());
        Image setIcon = imageIcon.getImage().getScaledInstance(150,150, Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(setIcon);
        
        //Set the choose file to label
        lImage.setIcon(img);
        
        //Get the path of the file selected
        String filePath = file.getAbsolutePath();
        tfImageLocation.setText(filePath);
        sourceFile = new File(filePath);
        
        //Get the extension of the file
        String extension = filePath.substring(filePath.lastIndexOf(".")+1);
        
        //Get the destination path of the file
        String destPath = "product/image/product"+ recordData[0]+ "." + extension;
        
        //Set the variable
        destinationFile = new File (destPath);
        desFileName = ("product"+ recordData[0]+ "." + extension);
    }//GEN-LAST:event_bChooseImageActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:
        if (tfName.getText().isEmpty() || tfPrice.getText().isEmpty()|| tfStock.getText().isEmpty()) {
            //Check if all the field is fille
            JOptionPane.showMessageDialog(null, "Please enter all fields.");
        }
        
        else {
            //Get the value from text field
            String name = tfName.getText();
            String category = (String) cbCategory.getSelectedItem();
            String price = tfPrice.getText();
            String stock = tfStock.getText();
            String status = (String) cbStatus.getSelectedItem();

             try{
                 //Check if the price is numeric
                Double.parseDouble(price);
            }

            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Please only insert numeric value in price.");
                return;
            }

            try{
                //Check if the price is integer
                Integer.parseInt(stock);
            }

            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Please only integer number in stock.");
                return;
            }




            //Change the recordData to new value
            recordData[1] = name;
            recordData[2] = category;
            recordData[3] = price;
            recordData[4] = stock;
            recordData[6] = status;
            if (desFileName != null) {
            //If choose a new image
             try {
                 //Delete the old image
                File oldFile = new File ("product\\image\\" + recordData[5]);
                oldFile.delete();
                
                
                //Replace with new image file
                Files.copy(sourceFile.toPath(), destinationFile.toPath());

            } catch (Exception e) {
                 System.out.println(e.getMessage());

            }
             //Replace the image name in record
            recordData[5] = desFileName;
            }



            try {
                //Get all the line in text file
                List<String> lines = fp.getAllProductRecord();
                
                //Set a new lines with new record
                String strRecord = Arrays.toString(recordData);
                strRecord = strRecord.replaceAll(", ", ",");
                strRecord = strRecord.substring(1, strRecord.length() - 1);
                lines.set(row, strRecord);

                //Write to the text file
                BufferedWriter writer = new BufferedWriter(new FileWriter("product\\product.txt"));
                for (String updatedLine : lines) {
                    writer.write(updatedLine);
                    writer.newLine();
                }

                writer.close();

                } 
             catch (Exception e) {
                System.err.println(e.getMessage());
            }
            //Show Succe4ssfully save and close
            JOptionPane.showMessageDialog(null, "Successfully Saved!");
            this.dispose();
        }
    //Then refresh the table at Admin Page
    adminPageInstance.refreshTable("");
    }//GEN-LAST:event_bSaveActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditProduct dialog = new EditProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private File sourceFile;
    private File destinationFile;
    private String desFileName;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bChooseImage;
    private javax.swing.JButton bSave;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel lCategory;
    private javax.swing.JLabel lImage;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lPrice;
    private javax.swing.JLabel lStatus;
    private javax.swing.JLabel lStock;
    private javax.swing.JLabel lTitle;
    private javax.swing.JTextField tfImageLocation;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfStock;
    // End of variables declaration//GEN-END:variables
}
